services:
  # Bot Instance 1 (Main Repository)
  bot_1:
    build: 
      context: .
    image: coinswitch-bot-1
    restart: unless-stopped
    container_name: coinswitch_bot_1
    env_file:
      - .env
    environment:
      - DATABASE_PATH=data/Crypto_Data.db
    volumes:
      - ./bot_data/bot_1:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Bot Instance 2 (Repo B)
  bot_2:
    build: 
      context: ./repos/bot_2
    image: coinswitch-bot-2
    restart: unless-stopped
    container_name: coinswitch_bot_2
    env_file:
      - .env
    environment:
      - DATABASE_PATH=data/Crypto_Data.db
    volumes:
      - ./bot_data/bot_2:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Bot Instance 3 (Repo C)
  bot_3:
    build: 
      context: ./repos/bot_3
    image: coinswitch-bot-3
    restart: unless-stopped
    container_name: coinswitch_bot_3
    env_file:
      - .env
    environment:
      - DATABASE_PATH=data/Crypto_Data.db
    volumes:
      - ./bot_data/bot_3:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
